### ISSUE TITLE
Implement "Reset Password" Feature

### ISSUE THREAD

**Issue by messismore** [brycecammo/RoaringApps#23]
I can not log into my account, because apparently my password is not correct. However, there is no way to reset it.

I created the account via Mozilla Persona, I do not remember to have set a password.

OSX 10.6.8 Safari 5.1.10 / Chromium 31.0.1627.0

**Comment by brycecammo** [comment]
Hi,

Unfortunately I'm waiting on a service provider to implement password resets, so cannot enable that feature until they do. If you created the account with Persona, are you able to log in via Persona as well?

**Comment by messismore** [comment]
![bildschirmfoto 2013-10-15 um 16 05 33](https://f.cloud.github.com/assets/5689189/1334110/e832263e-35a2-11e3-9ad4-9b80ddca29f1.png)
The Persona option no longer shows. (Since two weeks or so.)

**Comment by brycecammo** [comment]
Ah, you're right! Sorry about that. I was having some issues with Persona so disabled it while I sorted it out. I'm working on it right now.

**Comment by brycecammo** [comment]
I've just pushed an update that re-enabled Persona login. Let me know if you're still having issues logging in.

**Comment by messismore** [comment]
Still does not work, the Persona window appears and claims to be signing me in but this is not reflected on the Roaringapps site. Is there a way to manually delete my account, so I register the traditional way?
