### ISSUE TITLE
Allow favorites to be marked directly from compatibility table

### ISSUE THREAD

**Issue by jwhitley** [brycecammo/RoaringApps#26]
The current workflow for marking a set of favorites appears to be:
1.  Find the app in the table.
2.  Navigate to the app's detail page
3.  Hit the favorite star
4.  Return to the table to find the next app

Step 1 is awesomely fast in the real-time mode -- nice work!  Steps 2-4 are much, much slower and a clunky workflow if the goal is to simply wade in and mark a bunch of important/interesting apps as favorites.

Suggested improvement:

Add the ability to mark an app as favorite directly in the compatibility table.  That way I never need to leave the table when doing bulk marking of favorites.

**Comment by brycecammo** [comment]
John, that's a great idea! I'll work on implementing it when I get a chance. 

Note that when on an app's detail page, you can use the search function (top right) to look for apps & go to their respective pages without requiring a page reload, which might make the workflow a little quicker in the meantime.

**Comment by brycecammo** [comment]
I've finally implemented this feature. You can show/hide the favourites column on the compatibility table by clicking on the 'Options' button above the table.
